use ultimate_core::DataError;

#[tokio::main]
async fn main() -> Result<(), DataError> {
  Ok(())
}
